--- #YAML:1.0
name:               RTSP-Client
version:            0.1
abstract:           High-level client for the Real-Time Streaming Protocol
author:
    - Mischa Spiegelmock <revmischa@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:       0
    RTSP::Lite:  0.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
